version: '3.8'

services:
  # MariaDB Database
  database:
    image: mariadb:10.11-jammy
    container_name: greengroves_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: green_groves
      MYSQL_USER: greengroves_user
      MYSQL_PASSWORD: user_password_123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database:/docker-entrypoint-initdb.d
    networks:
      - greengroves_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: greengroves_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    depends_on:
      database:
        condition: service_healthy
    networks:
      - greengroves_network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: green_groves
      DB_USERNAME: greengroves_user
      DB_PASSWORD: user_password_123

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: greengroves_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - greengroves_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: greengroves_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - greengroves_network
    depends_on:
      - nginx

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: greengroves_phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_123
    ports:
      - "8080:80"
    networks:
      - greengroves_network

volumes:
  db_data:
    driver: local
  backend_vendor:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  greengroves_network:
    driver: bridge

