<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Accessory;

class AccessorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accessories = [
            // Găng tay và bảo hộ
            [
                'name' => 'Găng tay làm vườn chống nước',
                'slug' => 'gang-tay-lam-vuon-chong-nuoc',
                'description' => 'Găng tay làm vườn chống nước cao cấp, bảo vệ tay khỏi bụi bẩn, nước và các tác nhân gây hại. Chất liệu cotton pha polyester, thoáng khí và dễ giặt.',
                'price' => 45000,
                'image' => '/image.png',
                'category' => 'Bảo hộ',
                'material' => 'Cotton + Polyester',
                'size' => 'M',
                'color' => 'Xanh lá',
                'brand' => 'Garden Pro',
                'is_waterproof' => true,
                'is_durable' => true,
            ],
            [
                'name' => 'Găng tay làm vườn dài tay',
                'slug' => 'gang-tay-lam-vuon-dai-tay',
                'description' => 'Găng tay làm vườn dài tay bảo vệ toàn bộ cánh tay, chống côn trùng và gai cây. Chất liệu bền chắc, phù hợp cho công việc nặng.',
                'price' => 65000,
                'image' => '/image.png',
                'category' => 'Bảo hộ',
                'material' => 'Canvas',
                'size' => 'L',
                'color' => 'Nâu',
                'brand' => 'Heavy Duty',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Kính bảo hộ làm vườn',
                'slug' => 'kinh-bao-ho-lam-vuon',
                'description' => 'Kính bảo hộ chống bụi, côn trùng và tia UV. Thiết kế nhẹ, thoải mái và không bị mờ hơi. Phù hợp cho mọi hoạt động làm vườn.',
                'price' => 35000,
                'image' => '/image.png',
                'category' => 'Bảo hộ',
                'material' => 'Polycarbonate',
                'size' => 'One Size',
                'color' => 'Trong suốt',
                'brand' => 'Safety First',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Mũ nón làm vườn có lưới',
                'slug' => 'mu-non-lam-vuon-co-luoi',
                'description' => 'Mũ nón làm vườn có lưới chống côn trùng, che nắng và bảo vệ đầu. Thiết kế thoáng khí, dây đeo có thể điều chỉnh.',
                'price' => 55000,
                'image' => '/image.png',
                'category' => 'Bảo hộ',
                'material' => 'Cotton + Lưới',
                'size' => 'L',
                'color' => 'Xanh lá',
                'brand' => 'Sun Hat',
                'is_waterproof' => false,
                'is_durable' => true,
            ],

            // Ủng và giày
            [
                'name' => 'Ủng cao su làm vườn',
                'slug' => 'ung-cao-su-lam-vuon',
                'description' => 'Ủng cao su chống nước, dễ vệ sinh và bền chắc. Đế chống trượt, phù hợp cho mọi loại đất và thời tiết.',
                'price' => 120000,
                'image' => '/image.png',
                'category' => 'Giày dép',
                'material' => 'Cao su',
                'size' => '42',
                'color' => 'Xanh lá',
                'brand' => 'Rubber Boot',
                'is_waterproof' => true,
                'is_durable' => true,
            ],
            [
                'name' => 'Giày làm vườn thấp cổ',
                'slug' => 'giay-lam-vuon-thap-co',
                'description' => 'Giày làm vườn thấp cổ thoải mái, chống nước và dễ vệ sinh. Đế chống trượt, phù hợp cho công việc nhẹ.',
                'price' => 85000,
                'image' => '/image.png',
                'category' => 'Giày dép',
                'material' => 'PVC',
                'size' => '40',
                'color' => 'Đen',
                'brand' => 'Garden Shoe',
                'is_waterproof' => true,
                'is_durable' => true,
            ],

            // Túi và container
            [
                'name' => 'Túi đựng dụng cụ làm vườn',
                'slug' => 'tui-dung-dung-cu-lam-vuon',
                'description' => 'Túi đựng dụng cụ làm vườn có nhiều ngăn, dễ mang theo và tổ chức. Chất liệu bền chắc, chống nước nhẹ.',
                'price' => 75000,
                'image' => '/image.png',
                'category' => 'Túi đựng',
                'material' => 'Canvas',
                'size' => '30x20x15cm',
                'color' => 'Xanh rêu',
                'brand' => 'Tool Bag',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Xô nhựa đựng đất',
                'slug' => 'xo-nhua-dung-dat',
                'description' => 'Xô nhựa đựng đất, phân bón hoặc nước. Có quai xách tiện lợi, dễ vệ sinh và bền chắc.',
                'price' => 45000,
                'image' => '/image.png',
                'category' => 'Container',
                'material' => 'Nhựa HDPE',
                'size' => '10 lít',
                'color' => 'Trắng',
                'brand' => 'Plastic Bucket',
                'is_waterproof' => true,
                'is_durable' => true,
            ],
            [
                'name' => 'Khay ươm cây con',
                'slug' => 'khay-uom-cay-con',
                'description' => 'Khay ươm cây con có nhiều ô nhỏ, phù hợp cho việc gieo hạt và ươm cây con. Chất liệu nhựa bền, có lỗ thoát nước.',
                'price' => 35000,
                'image' => '/image.png',
                'category' => 'Container',
                'material' => 'Nhựa PP',
                'size' => '50 ô',
                'color' => 'Đen',
                'brand' => 'Seed Tray',
                'is_waterproof' => false,
                'is_durable' => true,
            ],

            // Dây buộc và hỗ trợ
            [
                'name' => 'Dây buộc cây tự phân hủy',
                'slug' => 'day-buoc-cay-tu-phan-huy',
                'description' => 'Dây buộc cây tự phân hủy thân thiện với môi trường. Bền chắc, dễ sử dụng và không gây hại cho cây trồng.',
                'price' => 25000,
                'image' => '/image.png',
                'category' => 'Dây buộc',
                'material' => 'Jute',
                'size' => '50m',
                'color' => 'Nâu',
                'brand' => 'Eco Tie',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Cọc treo cây leo',
                'slug' => 'coc-treo-cay-leo',
                'description' => 'Cọc treo cây leo bằng tre tự nhiên, bền chắc và thân thiện với môi trường. Phù hợp cho cà chua, dưa chuột và các cây leo khác.',
                'price' => 15000,
                'image' => '/image.png',
                'category' => 'Hỗ trợ cây',
                'material' => 'Tre',
                'size' => '1.5m',
                'color' => 'Nâu',
                'brand' => 'Bamboo Stake',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Lưới che nắng cho cây',
                'slug' => 'luoi-che-nang-cho-cay',
                'description' => 'Lưới che nắng cho cây giúp bảo vệ cây khỏi ánh nắng gay gắt. Chất liệu bền, chống tia UV và thoáng khí.',
                'price' => 95000,
                'image' => '/image.png',
                'category' => 'Bảo vệ cây',
                'material' => 'Polyethylene',
                'size' => '2x3m',
                'color' => 'Xanh lá',
                'brand' => 'Shade Net',
                'is_waterproof' => false,
                'is_durable' => true,
            ],

            // Nhãn và đánh dấu
            [
                'name' => 'Nhãn cây bằng gỗ',
                'slug' => 'nhan-cay-bang-go',
                'description' => 'Nhãn cây bằng gỗ tự nhiên, có thể viết bằng bút chì hoặc bút dạ. Bền chắc và thân thiện với môi trường.',
                'price' => 20000,
                'image' => '/image.png',
                'category' => 'Nhãn đánh dấu',
                'material' => 'Gỗ',
                'size' => '10x2cm',
                'color' => 'Nâu',
                'brand' => 'Wood Label',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Nhãn cây nhựa chống nước',
                'slug' => 'nhan-cay-nhua-chong-nuoc',
                'description' => 'Nhãn cây nhựa chống nước, có thể viết bằng bút dạ và không bị phai màu. Dễ vệ sinh và tái sử dụng.',
                'price' => 15000,
                'image' => '/image.png',
                'category' => 'Nhãn đánh dấu',
                'material' => 'Nhựa PVC',
                'size' => '8x1.5cm',
                'color' => 'Trắng',
                'brand' => 'Plastic Label',
                'is_waterproof' => true,
                'is_durable' => true,
            ],

            // Dụng cụ phụ trợ
            [
                'name' => 'Bình xịt nước mini',
                'slug' => 'binh-xit-nuoc-mini',
                'description' => 'Bình xịt nước mini tiện lợi cho việc tưới cây con và phun thuốc. Dung tích nhỏ gọn, dễ sử dụng.',
                'price' => 30000,
                'image' => '/image.png',
                'category' => 'Dụng cụ phụ trợ',
                'material' => 'Nhựa',
                'size' => '500ml',
                'color' => 'Xanh lá',
                'brand' => 'Spray Bottle',
                'is_waterproof' => true,
                'is_durable' => true,
            ],
            [
                'name' => 'Thước đo độ ẩm đất',
                'slug' => 'thuoc-do-do-am-dat',
                'description' => 'Thước đo độ ẩm đất giúp kiểm tra độ ẩm của đất trồng. Thiết kế đơn giản, dễ sử dụng và chính xác.',
                'price' => 40000,
                'image' => '/image.png',
                'category' => 'Dụng cụ đo lường',
                'material' => 'Nhựa + Kim loại',
                'size' => '20cm',
                'color' => 'Vàng',
                'brand' => 'Moisture Meter',
                'is_waterproof' => false,
                'is_durable' => true,
            ],
            [
                'name' => 'Băng keo làm vườn',
                'slug' => 'bang-keo-lam-vuon',
                'description' => 'Băng keo làm vườn chuyên dụng, chống nước và bền chắc. Dùng để buộc cây, che vết thương hoặc đánh dấu.',
                'price' => 18000,
                'image' => '/image.png',
                'category' => 'Dụng cụ phụ trợ',
                'material' => 'PVC',
                'size' => '5cm x 10m',
                'color' => 'Xanh lá',
                'brand' => 'Garden Tape',
                'is_waterproof' => true,
                'is_durable' => true,
            ],

            // Phụ kiện trang trí
            [
                'name' => 'Đèn LED trang trí vườn',
                'slug' => 'den-led-trang-tri-vuon',
                'description' => 'Đèn LED trang trí vườn chạy bằng năng lượng mặt trời. Tự động bật/tắt, tạo ánh sáng ấm áp cho khu vườn vào ban đêm.',
                'price' => 150000,
                'image' => '/image.png',
                'category' => 'Trang trí',
                'material' => 'Nhựa + LED',
                'size' => '30cm',
                'color' => 'Trắng',
                'brand' => 'Solar Light',
                'is_waterproof' => true,
                'is_durable' => true,
            ],
            [
                'name' => 'Tượng trang trí vườn nhỏ',
                'slug' => 'tuong-trang-tri-vuon-nho',
                'description' => 'Tượng trang trí vườn nhỏ bằng gốm sứ, tạo điểm nhấn cho khu vườn. Thiết kế đẹp mắt, chống nước và bền chắc.',
                'price' => 85000,
                'image' => '/image.png',
                'category' => 'Trang trí',
                'material' => 'Gốm sứ',
                'size' => '15cm',
                'color' => 'Nhiều màu',
                'brand' => 'Garden Decor',
                'is_waterproof' => true,
                'is_durable' => true,
            ]
        ];

        foreach ($accessories as $accessory) {
            Accessory::create($accessory);
        }
    }
}