<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Book;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            // Sách về trồng trọt cơ bản
            [
                'title' => 'Nghệ thuật làm vườn - Hướng dẫn toàn diện',
                'slug' => 'nghe-thuat-lam-vuon-huong-dan-toan-dien',
                'description' => 'Cuốn sách toàn diện về nghệ thuật làm vườn, từ những kiến thức cơ bản đến các kỹ thuật nâng cao. Phù hợp cho cả người mới bắt đầu và những người đã có kinh nghiệm.',
                'author' => 'Nguyễn Văn Hoa',
                'category' => 'Trồng trọt',
                'price' => 250000,
                'image' => '/image.png',
                'rating' => 4.8,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách trồng rau sạch tại nhà',
                'slug' => 'cach-trong-rau-sach-tai-nha',
                'description' => 'Hướng dẫn chi tiết cách trồng rau sạch tại nhà với các kỹ thuật đơn giản và hiệu quả. Bao gồm cách thiết kế vườn rau mini và chăm sóc cây trồng.',
                'author' => 'Trần Thị Mai',
                'category' => 'Trồng trọt',
                'price' => 180000,
                'image' => '/image.png',
                'rating' => 4.6,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Kỹ thuật trồng cây ăn quả trong chậu',
                'slug' => 'ky-thuat-trong-cay-an-qua-trong-chau',
                'description' => 'Hướng dẫn chi tiết cách trồng cây ăn quả trong chậu, từ chọn giống đến thu hoạch. Phù hợp cho những ai muốn có trái cây sạch nhưng không có đất vườn rộng.',
                'author' => 'Lê Văn Đức',
                'category' => 'Trồng trọt',
                'price' => 220000,
                'image' => '/image.png',
                'rating' => 4.7,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Bí quyết trồng hoa hồng đẹp nhất',
                'slug' => 'bi-quyet-trong-hoa-hong-dep-nhat',
                'description' => 'Bí quyết trồng và chăm sóc hoa hồng để có những bông hoa đẹp nhất. Bao gồm cách chọn giống, trồng cây, cắt tỉa và phòng trừ sâu bệnh.',
                'author' => 'Phạm Thị Lan',
                'category' => 'Trồng trọt',
                'price' => 200000,
                'image' => '/image.png',
                'rating' => 4.9,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Hướng dẫn trồng cây thủy canh',
                'slug' => 'huong-dan-trong-cay-thuy-canh',
                'description' => 'Học cách trồng cây thủy canh - phương pháp trồng cây không cần đất hiện đại. Hướng dẫn thiết kế hệ thống thủy canh đơn giản tại nhà.',
                'author' => 'Nguyễn Minh Tuấn',
                'category' => 'Trồng trọt',
                'price' => 300000,
                'image' => '/image.png',
                'rating' => 4.5,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],

            // Sách về chăm sóc cây
            [
                'title' => 'Cách chăm sóc cây cảnh luôn xanh tươi',
                'slug' => 'cach-cham-soc-cay-canh-luon-xanh-tuoi',
                'description' => 'Bí quyết chăm sóc cây cảnh để cây luôn xanh tươi và phát triển tốt. Bao gồm cách tưới nước, bón phân và tạo điều kiện tốt nhất cho cây.',
                'author' => 'Võ Thị Hương',
                'category' => 'Chăm sóc',
                'price' => 160000,
                'image' => '/image.png',
                'rating' => 4.4,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Kỹ thuật tưới nước hiệu quả cho cây trồng',
                'slug' => 'ky-thuat-tuoi-nuoc-hieu-qua-cho-cay-trong',
                'description' => 'Học cách tưới nước đúng cách cho từng loại cây. Hướng dẫn thời điểm tưới nước, lượng nước cần thiết và các kỹ thuật tưới nước hiệu quả.',
                'author' => 'Đặng Văn Nam',
                'category' => 'Chăm sóc',
                'price' => 140000,
                'image' => '/image.png',
                'rating' => 4.3,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách bón phân cho cây trồng đúng cách',
                'slug' => 'cach-bon-phan-cho-cay-trong-dung-cach',
                'description' => 'Hướng dẫn chi tiết cách bón phân cho cây trồng để cây phát triển tốt nhất. Bao gồm các loại phân, thời điểm bón phân và kỹ thuật bón phân.',
                'author' => 'Bùi Thị Thu',
                'category' => 'Chăm sóc',
                'price' => 170000,
                'image' => '/image.png',
                'rating' => 4.6,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Kỹ thuật cắt tỉa cây cảnh chuyên nghiệp',
                'slug' => 'ky-thuat-cat-tia-cay-canh-chuyen-nghiep',
                'description' => 'Học cách cắt tỉa cây cảnh để tạo hình đẹp và kích thích cây phát triển. Hướng dẫn các kỹ thuật cắt tỉa cơ bản và nâng cao.',
                'author' => 'Hoàng Văn Long',
                'category' => 'Chăm sóc',
                'price' => 190000,
                'image' => '/image.png',
                'rating' => 4.7,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách phòng trừ sâu bệnh cho cây trồng',
                'slug' => 'cach-phong-tru-sau-benh-cho-cay-trong',
                'description' => 'Hướng dẫn cách phòng trừ sâu bệnh cho cây trồng một cách tự nhiên và hiệu quả. Bao gồm cách nhận biết sâu bệnh và các phương pháp xử lý.',
                'author' => 'Lý Thị Hoa',
                'category' => 'Chăm sóc',
                'price' => 210000,
                'image' => '/image.png',
                'rating' => 4.8,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],

            // Sách về dụng cụ làm vườn
            [
                'title' => 'Dụng cụ làm vườn cần thiết cho người mới bắt đầu',
                'slug' => 'dung-cu-lam-vuon-can-thiet-cho-nguoi-moi-bat-dau',
                'description' => 'Giới thiệu các dụng cụ làm vườn cơ bản mà mọi người làm vườn nên có. Hướng dẫn cách chọn và sử dụng dụng cụ hiệu quả.',
                'author' => 'Trương Văn Minh',
                'category' => 'Dụng cụ',
                'price' => 120000,
                'image' => '/image.png',
                'rating' => 4.2,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách sử dụng kéo cắt cành an toàn và hiệu quả',
                'slug' => 'cach-su-dung-keo-cat-canh-an-toan-va-hieu-qua',
                'description' => 'Hướng dẫn chi tiết cách sử dụng kéo cắt cành an toàn và hiệu quả. Bao gồm cách chọn kéo phù hợp và kỹ thuật cắt tỉa đúng cách.',
                'author' => 'Ngô Thị Linh',
                'category' => 'Dụng cụ',
                'price' => 130000,
                'image' => '/image.png',
                'rating' => 4.4,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Hệ thống tưới nước tự động cho vườn nhà',
                'slug' => 'he-thong-tuoi-nuoc-tu-dong-cho-vuon-nha',
                'description' => 'Hướng dẫn thiết kế và lắp đặt hệ thống tưới nước tự động cho vườn nhà. Bao gồm cách chọn thiết bị và lắp đặt hệ thống.',
                'author' => 'Vũ Văn Hùng',
                'category' => 'Dụng cụ',
                'price' => 280000,
                'image' => '/image.png',
                'rating' => 4.6,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],

            // Sách về đất trồng và dinh dưỡng
            [
                'title' => 'Chọn đất trồng phù hợp cho từng loại cây',
                'slug' => 'chon-dat-trong-phu-hop-cho-tung-loai-cay',
                'description' => 'Hướng dẫn chọn loại đất trồng tốt nhất cho từng loại cây. Bao gồm các loại đất khác nhau và cách cải thiện đất trồng.',
                'author' => 'Đinh Thị Mai',
                'category' => 'Đất trồng',
                'price' => 150000,
                'image' => '/image.png',
                'rating' => 4.5,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách làm phân compost tại nhà',
                'slug' => 'cach-lam-phan-compost-tai-nha',
                'description' => 'Hướng dẫn chi tiết cách làm phân compost tại nhà từ rác thải hữu cơ. Bao gồm các bước làm phân compost và cách sử dụng hiệu quả.',
                'author' => 'Phan Văn Đức',
                'category' => 'Đất trồng',
                'price' => 110000,
                'image' => '/image.png',
                'rating' => 4.3,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách đo và điều chỉnh pH đất',
                'slug' => 'cach-do-va-dieu-chinh-ph-dat',
                'description' => 'Học cách đo và điều chỉnh pH đất để tạo điều kiện tốt nhất cho cây trồng. Hướng dẫn sử dụng máy đo pH và các phương pháp điều chỉnh.',
                'author' => 'Lê Thị Hương',
                'category' => 'Đất trồng',
                'price' => 160000,
                'image' => '/image.png',
                'rating' => 4.4,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],

            // Sách về chăm sóc theo mùa
            [
                'title' => 'Cách chăm sóc cây trong mùa đông',
                'slug' => 'cach-cham-soc-cay-trong-mua-dong',
                'description' => 'Hướng dẫn chăm sóc cây trồng trong mùa đông để cây sống sót và phát triển tốt. Bao gồm cách bảo vệ cây khỏi lạnh và tạo môi trường ấm áp.',
                'author' => 'Nguyễn Văn Tùng',
                'category' => 'Chăm sóc',
                'price' => 140000,
                'image' => '/image.png',
                'rating' => 4.2,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách chuẩn bị vườn cho mùa xuân',
                'slug' => 'cach-chuan-bi-vuon-cho-mua-xuan',
                'description' => 'Hướng dẫn chuẩn bị vườn cho mùa xuân để có một mùa trồng trọt thành công. Bao gồm cách làm đất, chọn giống và lập kế hoạch trồng trọt.',
                'author' => 'Trần Văn Hải',
                'category' => 'Trồng trọt',
                'price' => 130000,
                'image' => '/image.png',
                'rating' => 4.1,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách chăm sóc cây trong mùa hè nắng nóng',
                'slug' => 'cach-cham-soc-cay-trong-mua-he-nang-nong',
                'description' => 'Hướng dẫn chăm sóc cây trồng trong mùa hè nắng nóng để cây không bị héo và phát triển tốt. Bao gồm cách tưới nước và che chắn cây.',
                'author' => 'Võ Thị Lan',
                'category' => 'Chăm sóc',
                'price' => 150000,
                'image' => '/image.png',
                'rating' => 4.3,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],

            // Sách về nhân giống cây
            [
                'title' => 'Cách nhân giống cây trồng bằng giâm cành',
                'slug' => 'cach-nhan-giong-cay-trong-bang-giam-canh',
                'description' => 'Hướng dẫn chi tiết cách nhân giống cây trồng bằng phương pháp giâm cành. Bao gồm cách chọn cành giâm, chuẩn bị và chăm sóc cây con.',
                'author' => 'Đặng Văn Thành',
                'category' => 'Nhân giống',
                'price' => 170000,
                'image' => '/image.png',
                'rating' => 4.6,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Kỹ thuật chiết cành cây ăn quả',
                'slug' => 'ky-thuat-chiet-canh-cay-an-qua',
                'description' => 'Học kỹ thuật chiết cành cây ăn quả để có cây con khỏe mạnh. Hướng dẫn từng bước cách chiết cành và chăm sóc cây con.',
                'author' => 'Bùi Văn Dũng',
                'category' => 'Nhân giống',
                'price' => 200000,
                'image' => '/image.png',
                'rating' => 4.7,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ],
            [
                'title' => 'Cách gieo hạt và chăm sóc cây con',
                'slug' => 'cach-gieo-hat-va-cham-soc-cay-con',
                'description' => 'Hướng dẫn chi tiết cách gieo hạt và chăm sóc cây con từ khi nảy mầm đến khi trưởng thành. Bao gồm các kỹ thuật gieo hạt và chăm sóc cây con.',
                'author' => 'Lý Văn Hùng',
                'category' => 'Nhân giống',
                'price' => 180000,
                'image' => '/image.png',
                'rating' => 4.5,
                'buy_link' => 'https://example.com/buy',
                'borrowLink' => 'https://example.com/borrow',
            ]
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['slug' => $book['slug']],
                $book
            );
        }
    }
}
