version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11-jammy
    container_name: mariadb_green_groves
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: user_password_123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - db_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: phpmyadmin_green_groves
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_123
      MYSQL_ROOT_PASSWORD: root_password_123
    ports:
      - "8084:80"
    networks:
      - db_network

volumes:
  mariadb_data:

networks:
  db_network:
    driver: bridge